### ISSUE TITLE
Adding NAT

### ISSUE THREAD

**Issue by Dev-Romar** [travisghansen/pfsense_fauxapi_php_client#2]
How to add Rule and NAT.    

I used the following code below but it not working.

$data = [
        "nat" => [
            "rule" => [
                "source"=>[
                    "any"=>""
                ],
                "destination"=>[
                    "network"=>"wanip",
                    "port"=>"8080"
                ],
                "protocol"=>"tcp",
                "target"=>"192.168.10.300",
                "local-port"=>"5050",
                "interface"=>"wan"
            ]
        ]
    ];

    $response = $client->config_patch($data);
    var_dump($response);

**Comment by travisghansen** [comment]
What do you get in the response?

I honestly don't use the client as I decided to use the built-in xmlrpc service for my purposes. Your best bet is to ask on the primary project what's the correct syntax for updating NAT rules and they should know the correct structure.
